### PR TITLE
Fixes #5: set wkt obj datum_params if TOWGS84 is defined for datum

### LINKED ISSUE #5: TOWGS84 in datum is ignored
It should be parsed to datum_params

### PR DESCRIPTION
**Pull request by mbarto**

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
ok this looks good, though I need to make sure the data is returned in a way we can use

**Comment by mbarto** [comment]
Hi, any news on this?

**Comment by SimonA84** [comment]
I'm waiting for the fix with the datum_params too. When will it be merged?

**Comment by hccampos** [comment]
Same here, we just bumped into this bug in one of our projects using a `Belge 1972 / Belgian Lambert 72` projection because the parser matches the `belge` part of the name and then doesn't respect the `TOWG84` parameters.

@calvinmetcalf and @ahocevar is there any chance of having this merged anytime soon? Seems like the PR didn't get much attention.

**Comment by calvinmetcalf** [comment]
yeah I can merge it here, then if anyone can put in some test cases over at proj4js that would be helpful, so for example some wkt strings that didn't work before and do work now

**Pull request merged**
